### ISSUE TITLE
the attribute of the sqlite3 which is "check_same_thread" not supporting?

### ISSUE THREAD

**Issue by Yoonyoung-han** [smitchell556/cuttlepool#41]
I want to use the cuttlepool in multi thread envrionment, but it seems that it doesn't support the option of the sqlite3 ,"check_same_thread : False" .
Am I wrong or Do I have to look for other libraries?
self.pool = SQLitePool(factory=sqlite3.connect,capacity=4,database='/mnt/config/test.db',isolation_level=None,check_same_thread=False)

It is not working at all

**Comment by smitchell556** [comment]
What is the output when you try this?

There could be multiple reasons:
1. [SQLite is not being run/compiled with multi-threading enabled.](https://sqlite.org/threadsafe.html)
2. [You may have an older version of SQLite that does not support multi-threading.](https://docs.python.org/3/library/sqlite3.html#multithreading) In this case a newer version of SQLite would be needed.
3. There's a bug in CuttlePool, but I need a stack trace to figure that out.

I don't recommend using sqlite in a multi-threaded environment. Databases that use a server to handle incoming requests are a better choice for concurrent database operations. Since SQLite acts directly on the database file, accessing it concurrently can get hairy.

From the [`sqlite3.connect`](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect) docs:

> When using multiple threads with the same connection writing operations should be serialized by the user to avoid data corruption.

If you don't have a choice and need to use sqlite3 in a multi-threaded environment I highly recommend using a worker thread to handle all write operations and to feed it data from other threads through a [`queue.Queue`](https://docs.python.org/3/library/queue.html?highlight=queue#queue-objects) object.

In hindsight, I probably shouldn't have used sqlite3 as an example because it's not well suited for use in multi-threaded environments. I've been meaning to update the example to use MySQL (#40) or some other db that has a dedicated server since those are much more appropriate for use with CuttlePool. I'll fix that right now to prevent more confusion in the future.

**Comment by Yoonyoung-han** [comment]
I tested when I didn't used the cuttlepool and it is in multi thread env with sqlite3 . That point there wasn't situation that the database is locked(This is the race condition), and of course I used the option which is "check_same_thread" in sqlite3.connect. 
And then Using same code, the difference is  there is the cuttlepool. And the log appeared that database is locked .....
However, In this case, you don't recommend the cuttlepool? If you have some idea please help me.

**Comment by smitchell556** [comment]
Please post a copy of the code that doesn't work which uses cuttlepool and the code that does work which doesn't use cuttlepool and the error messages. I can't help without that information.

**Comment by Yoonyoung-han** [comment]
```
from db_base import DbBase

class TestSql(DbBase):
    def __init__(self):
        super().__init__()
    
    def insert_test(self,i):
        try:
            with self.pool.get_resource() as con:
                cur = con.cursor()
                sql = "INSERT INTO test(int_test, str_test) VALUES (%s,'insert_test')" % i
                cur.execute(sql,)
                cur.close()
        except Exception as e:
            print(e.args)
```

```
import sqlite3
from test_singleton import Singleton

import sys
sys.path.insert(0,'/usr/local/lib/python3.7/dist-packages')
from cuttlepool import CuttlePool

class SQLitePool(CuttlePool):
    def normalize_resource(self, resource):
        resource.row_factory = None
    def ping(self, resource):
        try:
            rv = resource.execute('SELECT 1').fetchall()
            return (1,) in rv
        except sqlite3.Error:
            return False

class DbBase(metaclass=Singleton):
    def __init__(self): 
        self.pool = SQLitePool(factory=sqlite3.connect, capacity=4,database='/mnt/config/test.db',isolation_level=None,check_same_thread=False)
```
```
# -*- coding: utf-8 -*-
import datetime
from test_sql import TestSql
import threading


def main():
    [TestSql().insert_test(i) for i in range(0,40000)]

if __name__ == '__main__':

    threads = []

    start_time = datetime.datetime.now()
    for i in range(4):
        threads.append(threading.Thread(target=main))
        threads[-1].start()
    main()
    mainThread = threading.currentThread()
    for thread in threading.enumerate():
        if thread is not mainThread:
            thread.join()
    end_time = datetime.datetime.now()
```

Those code make the error message 
![image](https://user-images.githubusercontent.com/49742899/94243192-0a187e80-ff52-11ea-932e-528fd6893b42.png)

but when I changed the code

```
import sqlite3
from test_singleton import Singleton

class DbBase(metaclass=Singleton):
    def __init__(self): 
        self.db_path = "/mnt/config/test.db"
        self.con = sqlite3.connect(self.db_path,isolation_level=None,check_same_thread=False)
```

like that, and no pool and It works
How can I do?

**Comment by smitchell556** [comment]
This is not a cuttlepool problem. SQLite is designed to lock the database when a connection is modifying it, preventing other connections from writing to it. This is where a database server shines because it's much better at handling concurrent writes from multiple connections.

This works:

```python
class DbBase(metaclass=Singleton):
    def __init__(self): 
        self.db_path = "/mnt/config/test.db"
        self.con = sqlite3.connect(self.db_path,isolation_level=None,check_same_thread=False)
```

because you are only using **_1_** connection.

This does not work:

```python
class SQLitePool(CuttlePool):
    def normalize_resource(self, resource):
        resource.row_factory = None
    def ping(self, resource):
        try:
            rv = resource.execute('SELECT 1').fetchall()
            return (1,) in rv
        except sqlite3.Error:
            return False

class DbBase(metaclass=Singleton):
    def __init__(self): 
        self.pool = SQLitePool(factory=sqlite3.connect, capacity=4,database='/mnt/config/test.db',isolation_level=None,check_same_thread=False)
```

because it creates _**multiple**_ connections and since you are modifying the database, one of the connections has the write lock which locks the database and prevents other connections from writing to the database.

From [`sqlite3.connect`](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect)

> **When a database is accessed by multiple connections, and one of the processes modifies the database, the SQLite database is locked until that transaction is committed.** The timeout parameter specifies how long the connection should wait for the lock to go away until raising an exception. The default for the timeout parameter is 5.0 (five seconds).

and

> By default, check_same_thread is True and only the creating thread may use the connection. If set False, the returned connection may be shared across multiple threads. **When using multiple threads with the same connection writing operations should be serialized by the user** to avoid data corruption.

I do not recommend writing to a sqlite db with one connection from multiple threads because multiple threads could insert data in a single transaction which can be a pain to trace where in the program a specific insert is coming from and throws any amount of determinism out the window.

There are a few solutions to your problem:

1. Have a dedicated worker thread for writing to the database and pass data that needs to be inserted in the db to that thread through a [queue](https://docs.python.org/3/library/queue.html#queue-objects). (This is what I would do, since it serializes writes).
1. [SQLAlchemy may have some facilities for threading + sqlite.](https://docs.sqlalchemy.org/en/13/dialects/sqlite.html?highlight=sqlite%20thread#pysqlite-threading-pooling) Can't guarantee SQLAlchemy will work for your needs, but maybe you can make it work?
1. You can use a global sqlite connection with `check_same_thread=False`. (Like I said above, I don't recommend this).
1. If you do want to use CuttlePool for this, then you should serialize writes using a mutex and ensure a commit is made before releasing the mutex. This will allow the connection doing the write to release the write lock on the database before another connection tries to write. (You can do the same with a global sqlite connection to)
1. Use a database that is built to handle concurrent operations and multiple connections like MySQL.
